version: '3.6'
services:
  app:
    image: golang:latest
    ports:
    - "8080:8080"
    volumes:
      - .:/go/src/app
    links:
      - postgres
    working_dir: /go/src/app
    command: go run cmd/gqlgen/server.go
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:
