version: '3.6'
services:
  app:
    image: golang:latest
    ports:
    - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgrespassword
      REDIS_ADDR: "redis:6379"
    volumes:
      - .:/go/src/app
    links:
      - postgres
      - redis
    working_dir: /go/src/app
    command: go run cmd/gqlgen/server.go
  postgres:
    image: postgres:12
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
  redis:
    image: redis:6.2
    ports:
    - "6379:6379"
volumes:
  db_data:
