// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Set struct {
	ID               int64   `json:"id"`
	Hash             string  `json:"Hash"`
	Members          []int64 `json:"members"`
	IntersectingSets []*Set  `json:"intersectingSets"`
}

type SetInput struct {
	Members []int64 `json:"members"`
}
